/*
STEP 1: Set up the necessary database, schema, and warehouse
*/

CREATE DATABASE IF NOT EXISTS CORTEX_SEARCH_TUTORIAL_DB;

CREATE OR REPLACE WAREHOUSE CORTEX_SEARCH_TUTORIAL_WH WITH
    WAREHOUSE_SIZE='X-SMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED=TRUE;

USE WAREHOUSE CORTEX_SEARCH_TUTORIAL_WH;